config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, presence: true
  def day
    created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
            <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">
                Entries for <%= day %>
            </h3>

            <nav class="level is-mobile">
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">calories</p>
                        <p class="title"><%= entries.pluck(:calories).sum%></p>
                    </div>
                </div>

                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">proteins</p>
                        <p class="title"><%= entries.pluck(:proteins).sum%></p>
                    </div>
                </div>

                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">carbohydrates</p>
                        <p class="title"><%= entries.pluck(:carbohydrates).sum%></p>
                    </div>
                </div>

                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">fats</p>
                        <p class="title"><%= entries.pluck(:fats).sum%></p>
                    </div>
                </div>
            </nav>
            <% entries.each do |entry| %>
                <%= link_to entry_path(entry) do %>
                    <div class="card">
                        <div class="card-content">
                            <strong> <%= entry.meal_type %></strong><br>
                            <%= entry.calories %> calories,
                            <%= entry.proteins %>g proteins,
                            <%= entry.carbohydrates %>g carbohydrates,
                            <%= entry.fats %>g fat
                        </div>      
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: 'label' %>
    <%= form.text_field :meal_type, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :calories, class: 'label' %>
    <%= form.number_field :calories, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: 'label' %>
    <%= form.number_field :proteins, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: 'label' %>
    <%= form.number_field :carbohydrates, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :fats, class: 'label' %>
    <%= form.number_field :fats, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-success' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered" mt-6>
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>

        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns  mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %></p>
        </header>
        <div class="card-content">
          <p><span class="has-text-weight-bold"><%= entry.calories %></span> claories</p>
          <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
          <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
          <p><span class="has-text-weight-bold"><%= entry.fats %></span>grams of fat</p>
          <p class="italic">Logged: <%= time_ago_in_words(entry.created_at)%></p>
        </div>
        <div class="card-footer">
          <%= link_to 'Show', entry, class: 'card-footer-item'%>
          <%= link_to 'Edit', edit_entry_path(entry), class: 'card-footer-item'%>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item'%>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to 'View all entries', archives_index_path, class: 'button is-link is-outlined is-centered' %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered" mt-6>
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>

        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do%>
<%= @entry.meal_type %> &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        Meal type:
        <%= @entry.meal_type %>
      </p>
      <div class="panel-bloc">
        Calories:
        <%= @entry.calories %>
      </div>
      <div class="panel-bloc">
        Proteins:
        <%= @entry.proteins %>
      </div>
      <div class="panel-bloc">
        Carbohydrates:
        <%= @entry.carbohydrates %>
      </div>
      <div class="panel-bloc">
        Fats:
        <%= @entry.fats %>
      </nav>

      <div class="columns is-mobile">
        <div class="column">
          <%= link_to 'Edit', edit_entry_path(@entry), class: 'button is-gray' %> |
          <%= link_to 'Delate', entry_path(@entry), method: :delete, data: { confirm: 'Are you sure?'}, class: 'button is-gray'  %>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>

    <%= render 'shared/header' %>
    <% if notice.present? %>
      <div class="notification is-link is-light" id="notice"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light" id="alert"><%= alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>  
    </div>  

  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><title>location-food</title><path d="M18 11v7a2 2 0 0 1-4 0v-5h-2V3a3 3 0 0 1 3-3h3v11zM4 10a2 2 0 0 1-2-2V1a1 1 0 0 1 2 0v4h1V1a1 1 0 0 1 2 0v4h1V1a1 1 0 0 1 2 0v7a2 2 0 0 1-2 2v8a2 2 0 0 1-4 0v-8z"></path></svg>
            <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
          <% end %>

          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to "Create new entry", new_entry_path, class: "button is-success" %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Foodlog
        <% end %>
      </h1>
    </div>
  </div>
</section>